spring.application.name=KDT_PJT

## Port Number
server.port=8080



## DB Setting
spring.datasource.url=jdbc:mysql://192.168.0.84:32933/team1_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=team1_user
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## mapper 위치 선언
mybatis.mapper-locations=classpath:/mapper/**/*.xml

## SQL Log
logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG
logging.level.java.sql=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.sqltiming=DEBUG


## cmmnMap
mybatis.type-aliases-package=com.kdt.KDT_PJT.cmmn.map

## view JSP 설정 (선택1)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.view.encoding=UTF-8

## view HTML 설정 (선택2)
# spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.mode=HTML