# 커스텀변수 선언
my:
  datasource:
    port: '32933'  # MySQL 커스텀 포트
    dbname: team2_db  # 데이터베이스 이름
    host: citek707.iptime.org  # 외부 DB 서버 주소

server:
  address: 0.0.0.0  # 외부에서도 접근 가능하게 설정
  port: '8080'  # 서버 포트 번호
  servlet:
    context-path: ''  # 루트 경로로 애플리케이션 실행

pagehelper:
  helperDialect: mysql  # 사용하는 DB 방언 (MySQL, Oracle 등)
  params: count=countSql  # count 쿼리 자동 생성 설정
  reasonable: 'true'  # 페이지 번호가 0이거나 음수면 1페이지로 자동 보정
  supportMethodsArguments: 'true'  # pageNum, pageSize 등의 파라미터 직접 전달 가능

logging:
  level:
    org:
      mybatis: 'DEBUG'  # MyBatis 관련 디버그 로그 출력
      apache:
        ibatis: 'DEBUG'  # iBatis 관련 디버그 로그 출력
    java:
      sql: 'DEBUG'  # SQL 로그 출력
    p6spy: INFO  # P6Spy를 통한 SQL 로그 레벨
    jdbc:
      sqlonly: 'DEBUG '  # JDBC 실행 SQL만 출력
      sqltiming: 'DEBUG'  # JDBC SQL 실행 시간 출력

spring:
# DB 연결 URL (host, port, dbname 변수를 이용해 구성)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버 클래스
    password: '1234'  # DB 비밀번호
    username: team2_user  # DB 사용자명
    url: jdbc:mysql://${my.datasource.host}:${my.datasource.port}/${my.datasource.dbname}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

#  JSP 사용시 주석해제
  mvc:
    view:
      prefix: /WEB-INF/views/  # JSP 파일이 위치한 디렉토리
      suffix: .jsp  # 뷰 파일 확장자
      encoding: UTF-8  # 뷰 인코딩 설정

# HTML사용시 주석해제    
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    #suffix: .mustache
#    encoding: UTF-8
#    mode: HTML

  servlet:
    multipart:
      enabled: 'true'  # 파일 업로드 활성화
      max-file-size: 10MB  # 단일 파일 최대 크기
      max-request-size: 10MB  # 요청 전체 크기 제한

  application:
    name: kdtpjt  # 스프링 애플리케이션 이름



mybatis:
  mapper-locations: classpath:/mapper/**/*.xml  # Mapper XML 파일 위치
  type-aliases-package: com.kdt.KDT_PJT.cmmn.map  # Alias 등록할 패키지 (예: CmmnMap)
  configuration:
    map-underscore-to-camel-case: 'true'  # DB 컬럼명과 Java camelCase 자동 매핑
